/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout_ouvrier (void);
GtkWidget* create_gestion_ouvrier (void);
GtkWidget* create_supprime_ouvrier (void);
GtkWidget* create_modifier_ouvrier (void);
GtkWidget* create_consulter_ouvrier (void);
GtkWidget* create_ouvrier_mois (void);
GtkWidget* create_affichage_abscence (void);
GtkWidget* create_affichage_ouvrier (void);
GtkWidget* create_avancement (void);
GtkWidget* create_abscence_indiv (void);
