/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajout_ouvrier (void)
{
  GtkWidget *ajout_ouvrier;
  GtkWidget *fixed2;
  GtkWidget *entryPrenom_ajout;
  GtkWidget *entryTelephone_ajout;
  GtkWidget *entryCIN_ajout;
  GtkWidget *entryNom_ajout;
  GtkWidget *image63;
  GtkWidget *label67;
  GtkWidget *labelNom1A;
  GtkWidget *labelPrenom1A;
  GtkWidget *labelTelephone;
  GtkWidget *labelCIN1A;
  GtkWidget *label66;
  GtkWidget *labelAjout;
  GtkWidget *button_home_ouv;
  GtkWidget *image65;
  GtkWidget *button_retour_ajout;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image64;
  GtkWidget *label82;
  GtkWidget *button_ajouter_ouv;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image45;
  GtkWidget *label69;

  ajout_ouvrier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_ouvrier), _("Ajout des ouvriers"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajout_ouvrier), fixed2);

  entryPrenom_ajout = gtk_entry_new ();
  gtk_widget_show (entryPrenom_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), entryPrenom_ajout, 184, 136);
  gtk_widget_set_size_request (entryPrenom_ajout, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrenom_ajout), 8226);

  entryTelephone_ajout = gtk_entry_new ();
  gtk_widget_show (entryTelephone_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), entryTelephone_ajout, 184, 192);
  gtk_widget_set_size_request (entryTelephone_ajout, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryTelephone_ajout), 8226);

  entryCIN_ajout = gtk_entry_new ();
  gtk_widget_show (entryCIN_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), entryCIN_ajout, 184, 248);
  gtk_widget_set_size_request (entryCIN_ajout, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCIN_ajout), 8226);

  entryNom_ajout = gtk_entry_new ();
  gtk_widget_show (entryNom_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), entryNom_ajout, 184, 80);
  gtk_widget_set_size_request (entryNom_ajout, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom_ajout), 8226);

  image63 = create_pixmap (ajout_ouvrier, "background.jpg");
  gtk_widget_show (image63);
  gtk_fixed_put (GTK_FIXED (fixed2), image63, 0, 0);
  gtk_widget_set_size_request (image63, 840, 464);

  label67 = gtk_label_new (_("<span foreground=\"blue\"><b><i>Veuillez entrer les cordonn\303\251es de l'ouvrier que vous desirez ajouter</i></b></span>"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed2), label67, 16, 16);
  gtk_widget_set_size_request (label67, 480, 25);
  gtk_label_set_use_markup (GTK_LABEL (label67), TRUE);

  labelNom1A = gtk_label_new (_("Nom :"));
  gtk_widget_show (labelNom1A);
  gtk_fixed_put (GTK_FIXED (fixed2), labelNom1A, 48, 88);
  gtk_widget_set_size_request (labelNom1A, 100, 25);

  labelPrenom1A = gtk_label_new (_("Prenom : "));
  gtk_widget_show (labelPrenom1A);
  gtk_fixed_put (GTK_FIXED (fixed2), labelPrenom1A, 56, 144);
  gtk_widget_set_size_request (labelPrenom1A, 100, 25);

  labelTelephone = gtk_label_new (_("T\303\251l\303\251phone :"));
  gtk_widget_show (labelTelephone);
  gtk_fixed_put (GTK_FIXED (fixed2), labelTelephone, 64, 200);
  gtk_widget_set_size_request (labelTelephone, 100, 25);

  labelCIN1A = gtk_label_new (_("CIN :"));
  gtk_widget_show (labelCIN1A);
  gtk_fixed_put (GTK_FIXED (fixed2), labelCIN1A, 56, 256);
  gtk_widget_set_size_request (labelCIN1A, 100, 25);

  label66 = gtk_label_new (_("<span foreground=\"red\"><i>Le num de CIN doit \303\252tre compos\303\251 exactement de 8 chiffres</i></span>"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed2), label66, 352, 256);
  gtk_widget_set_size_request (label66, 390, 17);
  gtk_label_set_use_markup (GTK_LABEL (label66), TRUE);

  labelAjout = gtk_label_new (_("<span foreground=\"red\"><b></b></span>"));
  gtk_widget_show (labelAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAjout, 104, 424);
  gtk_widget_set_size_request (labelAjout, 300, 30);
  gtk_label_set_use_markup (GTK_LABEL (labelAjout), TRUE);

  button_home_ouv = gtk_button_new ();
  gtk_widget_show (button_home_ouv);
  gtk_fixed_put (GTK_FIXED (fixed2), button_home_ouv, 784, 416);
  gtk_widget_set_size_request (button_home_ouv, 40, 35);

  image65 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image65);
  gtk_container_add (GTK_CONTAINER (button_home_ouv), image65);

  button_retour_ajout = gtk_button_new ();
  gtk_widget_show (button_retour_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), button_retour_ajout, 250, 350);
  gtk_widget_set_size_request (button_retour_ajout, 100, 40);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (button_retour_ajout), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image64 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image64);
  gtk_box_pack_start (GTK_BOX (hbox34), image64, FALSE, FALSE, 0);

  label82 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label82);
  gtk_box_pack_start (GTK_BOX (hbox34), label82, FALSE, FALSE, 0);

  button_ajouter_ouv = gtk_button_new ();
  gtk_widget_show (button_ajouter_ouv);
  gtk_fixed_put (GTK_FIXED (fixed2), button_ajouter_ouv, 55, 350);
  gtk_widget_set_size_request (button_ajouter_ouv, 150, 40);
  gtk_container_set_border_width (GTK_CONTAINER (button_ajouter_ouv), 3);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button_ajouter_ouv), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image45 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image45);
  gtk_box_pack_start (GTK_BOX (hbox25), image45, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("AJOUTER"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox25), label69, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_home_ouv, "clicked",
                    G_CALLBACK (on_buttonHome_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_ajout, "clicked",
                    G_CALLBACK (on_button_retour_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_ouv, "clicked",
                    G_CALLBACK (on_buttonAjouter1B_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_ouvrier, ajout_ouvrier, "ajout_ouvrier");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, entryPrenom_ajout, "entryPrenom_ajout");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, entryTelephone_ajout, "entryTelephone_ajout");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, entryCIN_ajout, "entryCIN_ajout");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, entryNom_ajout, "entryNom_ajout");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, image63, "image63");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, label67, "label67");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, labelNom1A, "labelNom1A");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, labelPrenom1A, "labelPrenom1A");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, labelTelephone, "labelTelephone");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, labelCIN1A, "labelCIN1A");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, label66, "label66");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, labelAjout, "labelAjout");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, button_home_ouv, "button_home_ouv");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, image65, "image65");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, button_retour_ajout, "button_retour_ajout");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, image64, "image64");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, label82, "label82");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, button_ajouter_ouv, "button_ajouter_ouv");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, image45, "image45");
  GLADE_HOOKUP_OBJECT (ajout_ouvrier, label69, "label69");

  return ajout_ouvrier;
}

GtkWidget*
create_gestion_ouvrier (void)
{
  GtkWidget *gestion_ouvrier;
  GtkWidget *fixed3;
  GtkWidget *image53;
  GtkWidget *label65;
  GtkWidget *buttonAjout1A;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image6;
  GtkWidget *label11;
  GtkWidget *buttonModifier;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image8;
  GtkWidget *label13;
  GtkWidget *buttonSupprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image7;
  GtkWidget *label12;
  GtkWidget *buttonConsulter;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label14;
  GtkWidget *button_gestion_aff_ouv;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image43;
  GtkWidget *label64;
  GtkWidget *image55;
  GtkWidget *button_home_principal;
  GtkWidget *image30;
  GtkWidget *button_avancement;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image54;
  GtkWidget *label79;
  GtkWidget *button_ouvrier_mois;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image21;
  GtkWidget *label39;

  gestion_ouvrier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_ouvrier), _("Gestion des ouvriers"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (gestion_ouvrier), fixed3);

  image53 = create_pixmap (gestion_ouvrier, "background.jpg");
  gtk_widget_show (image53);
  gtk_fixed_put (GTK_FIXED (fixed3), image53, 0, 0);
  gtk_widget_set_size_request (image53, 840, 472);

  label65 = gtk_label_new (_("<span foreground=\"blue\"><b><i>Bienvenue dans l'espace de gestion des ouvriers</i></b></span>"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed3), label65, 10, 10);
  gtk_widget_set_size_request (label65, 360, 25);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  buttonAjout1A = gtk_button_new ();
  gtk_widget_show (buttonAjout1A);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonAjout1A, 100, 40);
  gtk_widget_set_size_request (buttonAjout1A, 150, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonAjout1A), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox3), image6, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, FALSE, FALSE, 0);

  buttonModifier = gtk_button_new ();
  gtk_widget_show (buttonModifier);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonModifier, 100, 90);
  gtk_widget_set_size_request (buttonModifier, 150, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonModifier), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox5), image8, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox5), label13, FALSE, FALSE, 0);

  buttonSupprimer = gtk_button_new ();
  gtk_widget_show (buttonSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonSupprimer, 100, 140);
  gtk_widget_set_size_request (buttonSupprimer, 150, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonSupprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox4), image7, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox4), label12, FALSE, FALSE, 0);

  buttonConsulter = gtk_button_new ();
  gtk_widget_show (buttonConsulter);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonConsulter, 100, 190);
  gtk_widget_set_size_request (buttonConsulter, 150, 40);
  gtk_container_set_border_width (GTK_CONTAINER (buttonConsulter), 1);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonConsulter), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Consulter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox6), label14, FALSE, FALSE, 0);

  button_gestion_aff_ouv = gtk_button_new ();
  gtk_widget_show (button_gestion_aff_ouv);
  gtk_fixed_put (GTK_FIXED (fixed3), button_gestion_aff_ouv, 10, 420);
  gtk_widget_set_size_request (button_gestion_aff_ouv, 150, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button_gestion_aff_ouv), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image43 = gtk_image_new_from_stock ("gtk-select-all", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_box_pack_start (GTK_BOX (hbox23), image43, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("Liste des ouvriers"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox23), label64, FALSE, FALSE, 0);

  image55 = create_pixmap (gestion_ouvrier, "home12.png");
  gtk_widget_show (image55);
  gtk_fixed_put (GTK_FIXED (fixed3), image55, 416, 40);
  gtk_widget_set_size_request (image55, 312, 389);

  button_home_principal = gtk_button_new ();
  gtk_widget_show (button_home_principal);
  gtk_fixed_put (GTK_FIXED (fixed3), button_home_principal, 768, 432);
  gtk_widget_set_size_request (button_home_principal, 66, 29);

  image30 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_container_add (GTK_CONTAINER (button_home_principal), image30);

  button_avancement = gtk_button_new ();
  gtk_widget_show (button_avancement);
  gtk_fixed_put (GTK_FIXED (fixed3), button_avancement, 100, 240);
  gtk_widget_set_size_request (button_avancement, 150, 40);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (button_avancement), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image54 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image54);
  gtk_box_pack_start (GTK_BOX (hbox31), image54, FALSE, FALSE, 0);

  label79 = gtk_label_new_with_mnemonic (_("Avancement"));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (hbox31), label79, FALSE, FALSE, 0);

  button_ouvrier_mois = gtk_button_new ();
  gtk_widget_show (button_ouvrier_mois);
  gtk_fixed_put (GTK_FIXED (fixed3), button_ouvrier_mois, 180, 420);
  gtk_widget_set_size_request (button_ouvrier_mois, 150, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_ouvrier_mois), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image21 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox11), image21, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Ouvrier du mois"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox11), label39, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonAjout1A, "clicked",
                    G_CALLBACK (on_buttonAjout1A_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifier, "clicked",
                    G_CALLBACK (on_buttonModifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimer, "clicked",
                    G_CALLBACK (on_buttonSupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonConsulter, "clicked",
                    G_CALLBACK (on_buttonConsulter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gestion_aff_ouv, "clicked",
                    G_CALLBACK (on_button_gestion_aff_ouv_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_avancement, "clicked",
                    G_CALLBACK (on_button_avancement_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ouvrier_mois, "clicked",
                    G_CALLBACK (on_button_ouvrier_mois_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_ouvrier, gestion_ouvrier, "gestion_ouvrier");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, image53, "image53");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, label65, "label65");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, buttonAjout1A, "buttonAjout1A");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, label11, "label11");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, buttonModifier, "buttonModifier");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, label13, "label13");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, buttonSupprimer, "buttonSupprimer");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, label12, "label12");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, buttonConsulter, "buttonConsulter");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, label14, "label14");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, button_gestion_aff_ouv, "button_gestion_aff_ouv");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, image43, "image43");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, label64, "label64");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, image55, "image55");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, button_home_principal, "button_home_principal");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, image30, "image30");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, button_avancement, "button_avancement");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, image54, "image54");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, label79, "label79");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, button_ouvrier_mois, "button_ouvrier_mois");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, image21, "image21");
  GLADE_HOOKUP_OBJECT (gestion_ouvrier, label39, "label39");

  return gestion_ouvrier;
}

GtkWidget*
create_supprime_ouvrier (void)
{
  GtkWidget *supprime_ouvrier;
  GtkWidget *fixed4;
  GtkWidget *entryCIN_supp;
  GtkWidget *labelCIN_supp1;
  GtkWidget *label61;
  GtkWidget *buttonCIN_supp;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *label28;
  GtkWidget *button_home_supp;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image57;
  GtkWidget *label81;
  GtkWidget *labelSupp;
  GtkWidget *button_retour_supp_ouv;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image56;
  GtkWidget *label80;

  supprime_ouvrier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprime_ouvrier), _("Supprimer un ouvrier"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (supprime_ouvrier), fixed4);

  entryCIN_supp = gtk_entry_new ();
  gtk_widget_show (entryCIN_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), entryCIN_supp, 144, 136);
  gtk_widget_set_size_request (entryCIN_supp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCIN_supp), 8226);

  labelCIN_supp1 = gtk_label_new_with_mnemonic (_(" <span foreground=\"blue\"><i><b>Veuillez inserer le CIN de l'ouvrier a Supprimer</b></i></span>"));
  gtk_widget_show (labelCIN_supp1);
  gtk_fixed_put (GTK_FIXED (fixed4), labelCIN_supp1, 16, 88);
  gtk_widget_set_size_request (labelCIN_supp1, 400, 30);
  gtk_label_set_use_markup (GTK_LABEL (labelCIN_supp1), TRUE);

  label61 = gtk_label_new (_("<i> ** Un numero de CIN doit etre compos\303\251 exactement de 8 chiffres  </i>"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed4), label61, 24, 168);
  gtk_widget_set_size_request (label61, 450, 17);
  gtk_label_set_use_markup (GTK_LABEL (label61), TRUE);
  gtk_misc_set_padding (GTK_MISC (label61), 4, 0);

  buttonCIN_supp = gtk_button_new ();
  gtk_widget_show (buttonCIN_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonCIN_supp, 60, 230);
  gtk_widget_set_size_request (buttonCIN_supp, 115, 35);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonCIN_supp), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_(" Supprimer"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox8), label28, FALSE, FALSE, 0);

  button_home_supp = gtk_button_new ();
  gtk_widget_show (button_home_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), button_home_supp, 350, 230);
  gtk_widget_set_size_request (button_home_supp, 40, 35);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (button_home_supp), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image57 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image57);
  gtk_box_pack_start (GTK_BOX (hbox33), image57, FALSE, FALSE, 0);

  label81 = gtk_label_new_with_mnemonic (_("\n"));
  gtk_widget_show (label81);
  gtk_box_pack_start (GTK_BOX (hbox33), label81, FALSE, FALSE, 0);

  labelSupp = gtk_label_new (_("<span foreground=\"red\"><b></b></span>"));
  gtk_widget_show (labelSupp);
  gtk_fixed_put (GTK_FIXED (fixed4), labelSupp, 128, 408);
  gtk_widget_set_size_request (labelSupp, 200, 30);
  gtk_label_set_use_markup (GTK_LABEL (labelSupp), TRUE);

  button_retour_supp_ouv = gtk_button_new ();
  gtk_widget_show (button_retour_supp_ouv);
  gtk_fixed_put (GTK_FIXED (fixed4), button_retour_supp_ouv, 200, 230);
  gtk_widget_set_size_request (button_retour_supp_ouv, 115, 35);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (button_retour_supp_ouv), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image56 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image56);
  gtk_box_pack_start (GTK_BOX (hbox32), image56, FALSE, FALSE, 0);

  label80 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label80);
  gtk_box_pack_start (GTK_BOX (hbox32), label80, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonCIN_supp, "clicked",
                    G_CALLBACK (on_buttonCIN_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_home_supp, "clicked",
                    G_CALLBACK (on_buttonHome_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_supp_ouv, "clicked",
                    G_CALLBACK (on_button_retour_supp_ouv_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprime_ouvrier, supprime_ouvrier, "supprime_ouvrier");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, entryCIN_supp, "entryCIN_supp");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, labelCIN_supp1, "labelCIN_supp1");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, label61, "label61");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, buttonCIN_supp, "buttonCIN_supp");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, image12, "image12");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, label28, "label28");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, button_home_supp, "button_home_supp");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, image57, "image57");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, label81, "label81");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, labelSupp, "labelSupp");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, button_retour_supp_ouv, "button_retour_supp_ouv");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, image56, "image56");
  GLADE_HOOKUP_OBJECT (supprime_ouvrier, label80, "label80");

  return supprime_ouvrier;
}

GtkWidget*
create_modifier_ouvrier (void)
{
  GtkWidget *modifier_ouvrier;
  GtkWidget *fixed5;
  GtkWidget *entry_cin_modif;
  GtkWidget *entry_info_modif;
  GtkWidget *image36;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *labelmsg_modif;
  GtkWidget *image40;
  GtkWidget *label_modif_reussi;
  GtkWidget *combobox1_modif;
  GtkWidget *buttonVerif_modif;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image28;
  GtkWidget *label53;
  GtkWidget *buttonHome_modif;
  GtkWidget *image39;
  GtkWidget *button_aff_modif;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image38;
  GtkWidget *label59;
  GtkWidget *buttonRetourModif;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image37;
  GtkWidget *label58;

  modifier_ouvrier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_ouvrier), _("Modifier"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (modifier_ouvrier), fixed5);

  entry_cin_modif = gtk_entry_new ();
  gtk_widget_show (entry_cin_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_cin_modif, 120, 104);
  gtk_widget_set_size_request (entry_cin_modif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin_modif), 8226);

  entry_info_modif = gtk_entry_new ();
  gtk_widget_show (entry_info_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_info_modif, 264, 264);
  gtk_widget_set_size_request (entry_info_modif, 120, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_info_modif), 8226);

  image36 = create_pixmap (modifier_ouvrier, "background.jpg");
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed5), image36, 0, 0);
  gtk_widget_set_size_request (image36, 840, 472);

  label50 = gtk_label_new (_("<span foreground=\"blue\"><b>Type de modification : </b></span>"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed5), label50, 32, 208);
  gtk_widget_set_size_request (label50, 170, 30);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  label51 = gtk_label_new (_("<span foreground=\"blue\"><b>Information modifi\303\251e : </b></span>"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed5), label51, 32, 264);
  gtk_widget_set_size_request (label51, 170, 30);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  labelmsg_modif = gtk_label_new (_("<span foreground=\"blue\"><b>Veuillez ins\303\250rer le CIN de l'ouvrier a modifier : </b></span>"));
  gtk_widget_show (labelmsg_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), labelmsg_modif, 32, 80);
  gtk_widget_set_size_request (labelmsg_modif, 370, 20);
  gtk_label_set_use_markup (GTK_LABEL (labelmsg_modif), TRUE);

  image40 = create_pixmap (modifier_ouvrier, "employee.png");
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed5), image40, 488, 32);
  gtk_widget_set_size_request (image40, 288, 400);

  label_modif_reussi = gtk_label_new ("");
  gtk_widget_show (label_modif_reussi);
  gtk_fixed_put (GTK_FIXED (fixed5), label_modif_reussi, 120, 312);
  gtk_widget_set_size_request (label_modif_reussi, 220, 30);

  combobox1_modif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combobox1_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox1_modif, 224, 208);
  gtk_widget_set_size_request (combobox1_modif, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_modif), _("1-Nom\t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_modif), _("2-Prenom"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_modif), _("3-Numero du telephone"));

  buttonVerif_modif = gtk_button_new ();
  gtk_widget_show (buttonVerif_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonVerif_modif, 320, 352);
  gtk_widget_set_size_request (buttonVerif_modif, 100, 30);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonVerif_modif), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image28 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox17), image28, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox17), label53, FALSE, FALSE, 0);

  buttonHome_modif = gtk_button_new ();
  gtk_widget_show (buttonHome_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonHome_modif, 216, 432);
  gtk_widget_set_size_request (buttonHome_modif, 40, 30);

  image39 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_container_add (GTK_CONTAINER (buttonHome_modif), image39);

  button_aff_modif = gtk_button_new ();
  gtk_widget_show (button_aff_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), button_aff_modif, 184, 352);
  gtk_widget_set_size_request (button_aff_modif, 100, 30);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button_aff_modif), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image38 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox21), image38, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Affichage"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox21), label59, FALSE, FALSE, 0);

  buttonRetourModif = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed5), buttonRetourModif, 55, 350);
  gtk_widget_set_size_request (buttonRetourModif, 100, 30);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttonRetourModif), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image37 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox20), image37, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox20), label58, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonVerif_modif, "clicked",
                    G_CALLBACK (on_buttonVerif_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonHome_modif, "clicked",
                    G_CALLBACK (on_buttonHome_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aff_modif, "clicked",
                    G_CALLBACK (on_button_aff_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRetourModif, "clicked",
                    G_CALLBACK (on_buttonRetourModif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_ouvrier, modifier_ouvrier, "modifier_ouvrier");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, entry_cin_modif, "entry_cin_modif");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, entry_info_modif, "entry_info_modif");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, image36, "image36");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, label50, "label50");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, label51, "label51");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, labelmsg_modif, "labelmsg_modif");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, image40, "image40");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, label_modif_reussi, "label_modif_reussi");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, combobox1_modif, "combobox1_modif");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, buttonVerif_modif, "buttonVerif_modif");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, image28, "image28");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, label53, "label53");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, buttonHome_modif, "buttonHome_modif");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, image39, "image39");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, button_aff_modif, "button_aff_modif");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, image38, "image38");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, label59, "label59");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, buttonRetourModif, "buttonRetourModif");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, image37, "image37");
  GLADE_HOOKUP_OBJECT (modifier_ouvrier, label58, "label58");

  return modifier_ouvrier;
}

GtkWidget*
create_consulter_ouvrier (void)
{
  GtkWidget *consulter_ouvrier;
  GtkWidget *fixed6;
  GtkWidget *entry_cin_consulter;
  GtkWidget *calendar_abs;
  GtkWidget *image35;
  GtkWidget *buttonHome_consult;
  GtkWidget *image33;
  GtkWidget *labelabs_reussit;
  GtkWidget *label_consult;
  GtkWidget *buttonRetour_consulter;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image34;
  GtkWidget *label57;
  GtkWidget *buttonAfficheAbs;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image27;
  GtkWidget *label49;
  GtkWidget *button_chercher_abs;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image44;
  GtkWidget *label68;
  GtkWidget *button_consult;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image20;
  GtkWidget *label38;

  consulter_ouvrier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (consulter_ouvrier), _("Consulter"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (consulter_ouvrier), fixed6);

  entry_cin_consulter = gtk_entry_new ();
  gtk_widget_show (entry_cin_consulter);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_cin_consulter, 560, 232);
  gtk_widget_set_size_request (entry_cin_consulter, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin_consulter), 8226);

  calendar_abs = gtk_calendar_new ();
  gtk_widget_show (calendar_abs);
  gtk_fixed_put (GTK_FIXED (fixed6), calendar_abs, 96, 136);
  gtk_widget_set_size_request (calendar_abs, 312, 216);
  gtk_calendar_display_options (GTK_CALENDAR (calendar_abs),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  image35 = create_pixmap (consulter_ouvrier, "background.jpg");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed6), image35, 0, 0);
  gtk_widget_set_size_request (image35, 840, 472);

  buttonHome_consult = gtk_button_new ();
  gtk_widget_show (buttonHome_consult);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonHome_consult, 792, 424);
  gtk_widget_set_size_request (buttonHome_consult, 35, 35);

  image33 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_container_add (GTK_CONTAINER (buttonHome_consult), image33);

  labelabs_reussit = gtk_label_new ("");
  gtk_widget_show (labelabs_reussit);
  gtk_fixed_put (GTK_FIXED (fixed6), labelabs_reussit, 500, 376);
  gtk_widget_set_size_request (labelabs_reussit, 330, 25);

  label_consult = gtk_label_new (_("<span foreground=\"blue\"><b>Inserez le CIN de l'ouvrier Absent :</b></span>"));
  gtk_widget_show (label_consult);
  gtk_fixed_put (GTK_FIXED (fixed6), label_consult, 520, 200);
  gtk_widget_set_size_request (label_consult, 250, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_consult), TRUE);

  buttonRetour_consulter = gtk_button_new ();
  gtk_widget_show (buttonRetour_consulter);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonRetour_consulter, 600, 328);
  gtk_widget_set_size_request (buttonRetour_consulter, 80, 35);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonRetour_consulter), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image34 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox19), image34, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox19), label57, FALSE, FALSE, 0);

  buttonAfficheAbs = gtk_button_new ();
  gtk_widget_show (buttonAfficheAbs);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonAfficheAbs, 592, 280);
  gtk_widget_set_size_request (buttonAfficheAbs, 100, 30);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonAfficheAbs), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image27 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox16), image27, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Affichage"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox16), label49, FALSE, FALSE, 0);

  button_chercher_abs = gtk_button_new ();
  gtk_widget_show (button_chercher_abs);
  gtk_fixed_put (GTK_FIXED (fixed6), button_chercher_abs, 720, 280);
  gtk_widget_set_size_request (button_chercher_abs, 100, 30);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button_chercher_abs), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image44 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image44);
  gtk_box_pack_start (GTK_BOX (hbox24), image44, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox24), label68, FALSE, FALSE, 0);

  button_consult = gtk_button_new ();
  gtk_widget_show (button_consult);
  gtk_fixed_put (GTK_FIXED (fixed6), button_consult, 464, 280);
  gtk_widget_set_size_request (button_consult, 100, 30);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_consult), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image20 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox10), image20, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox10), label38, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) calendar_abs, "day_selected",
                    G_CALLBACK (on_calendar_abs_day_selected),
                    NULL);
  g_signal_connect ((gpointer) buttonHome_consult, "clicked",
                    G_CALLBACK (on_buttonHome_consult_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRetour_consulter, "clicked",
                    G_CALLBACK (on_buttonRetour_consulter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAfficheAbs, "clicked",
                    G_CALLBACK (on_buttonAfficheAbs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_chercher_abs, "clicked",
                    G_CALLBACK (on_button_chercher_abs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_consult, "clicked",
                    G_CALLBACK (on_button_consult_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (consulter_ouvrier, consulter_ouvrier, "consulter_ouvrier");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, entry_cin_consulter, "entry_cin_consulter");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, calendar_abs, "calendar_abs");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, image35, "image35");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, buttonHome_consult, "buttonHome_consult");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, image33, "image33");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, labelabs_reussit, "labelabs_reussit");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, label_consult, "label_consult");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, buttonRetour_consulter, "buttonRetour_consulter");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, image34, "image34");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, label57, "label57");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, buttonAfficheAbs, "buttonAfficheAbs");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, image27, "image27");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, label49, "label49");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, button_chercher_abs, "button_chercher_abs");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, image44, "image44");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, label68, "label68");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, button_consult, "button_consult");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, image20, "image20");
  GLADE_HOOKUP_OBJECT (consulter_ouvrier, label38, "label38");

  return consulter_ouvrier;
}

GtkWidget*
create_ouvrier_mois (void)
{
  GtkWidget *ouvrier_mois;
  GtkWidget *fixed7;
  GtkWidget *image58;
  GtkWidget *image59;
  GtkWidget *sortiebestm;
  GtkWidget *label_ouvrier_mois;

  ouvrier_mois = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ouvrier_mois), _("Ouvrier du Mois"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (ouvrier_mois), fixed7);

  image58 = create_pixmap (ouvrier_mois, "background.jpg");
  gtk_widget_show (image58);
  gtk_fixed_put (GTK_FIXED (fixed7), image58, 0, 0);
  gtk_widget_set_size_request (image58, 840, 472);

  image59 = create_pixmap (ouvrier_mois, "unnamed (2) (1).png");
  gtk_widget_show (image59);
  gtk_fixed_put (GTK_FIXED (fixed7), image59, 472, 128);
  gtk_widget_set_size_request (image59, 320, 245);

  sortiebestm = gtk_label_new ("");
  gtk_widget_show (sortiebestm);
  gtk_fixed_put (GTK_FIXED (fixed7), sortiebestm, 248, 512);
  gtk_widget_set_size_request (sortiebestm, 300, 30);

  label_ouvrier_mois = gtk_label_new (_("<span foreground =\"blue\"><b>Ouvrier du Mois est : </b></span>"));
  gtk_widget_show (label_ouvrier_mois);
  gtk_fixed_put (GTK_FIXED (fixed7), label_ouvrier_mois, 8, 288);
  gtk_widget_set_size_request (label_ouvrier_mois, 350, 32);
  gtk_label_set_use_markup (GTK_LABEL (label_ouvrier_mois), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_ouvrier_mois), 0.05, 0.5);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ouvrier_mois, ouvrier_mois, "ouvrier_mois");
  GLADE_HOOKUP_OBJECT (ouvrier_mois, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (ouvrier_mois, image58, "image58");
  GLADE_HOOKUP_OBJECT (ouvrier_mois, image59, "image59");
  GLADE_HOOKUP_OBJECT (ouvrier_mois, sortiebestm, "sortiebestm");
  GLADE_HOOKUP_OBJECT (ouvrier_mois, label_ouvrier_mois, "label_ouvrier_mois");

  return ouvrier_mois;
}

GtkWidget*
create_affichage_abscence (void)
{
  GtkWidget *affichage_abscence;
  GtkWidget *fixed8;
  GtkWidget *treeview_abs;
  GtkWidget *image60;
  GtkWidget *btn_home_aff;
  GtkWidget *image32;
  GtkWidget *buttonRetour_aff_abs;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image31;
  GtkWidget *label56;

  affichage_abscence = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage_abscence), _("Affichage des abscences"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (affichage_abscence), fixed8);

  treeview_abs = gtk_tree_view_new ();
  gtk_widget_show (treeview_abs);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview_abs, 96, 56);
  gtk_widget_set_size_request (treeview_abs, 300, 200);

  image60 = create_pixmap (affichage_abscence, "background.jpg");
  gtk_widget_show (image60);
  gtk_fixed_put (GTK_FIXED (fixed8), image60, 0, 0);
  gtk_widget_set_size_request (image60, 840, 448);

  btn_home_aff = gtk_button_new ();
  gtk_widget_show (btn_home_aff);
  gtk_fixed_put (GTK_FIXED (fixed8), btn_home_aff, 400, 352);
  gtk_widget_set_size_request (btn_home_aff, 45, 35);

  image32 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_container_add (GTK_CONTAINER (btn_home_aff), image32);

  buttonRetour_aff_abs = gtk_button_new ();
  gtk_widget_show (buttonRetour_aff_abs);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonRetour_aff_abs, 272, 352);
  gtk_widget_set_size_request (buttonRetour_aff_abs, 100, 35);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonRetour_aff_abs), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image31 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox18), image31, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox18), label56, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_abs, "row_activated",
                    G_CALLBACK (on_treeview_abs_row_activated),
                    NULL);
  g_signal_connect ((gpointer) btn_home_aff, "clicked",
                    G_CALLBACK (on_btn_home_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRetour_aff_abs, "clicked",
                    G_CALLBACK (on_buttonRetour_aff_abs_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage_abscence, affichage_abscence, "affichage_abscence");
  GLADE_HOOKUP_OBJECT (affichage_abscence, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (affichage_abscence, treeview_abs, "treeview_abs");
  GLADE_HOOKUP_OBJECT (affichage_abscence, image60, "image60");
  GLADE_HOOKUP_OBJECT (affichage_abscence, btn_home_aff, "btn_home_aff");
  GLADE_HOOKUP_OBJECT (affichage_abscence, image32, "image32");
  GLADE_HOOKUP_OBJECT (affichage_abscence, buttonRetour_aff_abs, "buttonRetour_aff_abs");
  GLADE_HOOKUP_OBJECT (affichage_abscence, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (affichage_abscence, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (affichage_abscence, image31, "image31");
  GLADE_HOOKUP_OBJECT (affichage_abscence, label56, "label56");

  return affichage_abscence;
}

GtkWidget*
create_affichage_ouvrier (void)
{
  GtkWidget *affichage_ouvrier;
  GtkWidget *fixed9;
  GtkWidget *O_treeview;
  GtkWidget *image62;
  GtkWidget *button_home_list_ouv;
  GtkWidget *image61;
  GtkWidget *button_retour_aff_ouv;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image41;
  GtkWidget *label62;

  affichage_ouvrier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage_ouvrier), _("Liste des ouvriers"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (affichage_ouvrier), fixed9);

  O_treeview = gtk_tree_view_new ();
  gtk_widget_show (O_treeview);
  gtk_fixed_put (GTK_FIXED (fixed9), O_treeview, 232, 96);
  gtk_widget_set_size_request (O_treeview, 300, 200);

  image62 = create_pixmap (affichage_ouvrier, "background.jpg");
  gtk_widget_show (image62);
  gtk_fixed_put (GTK_FIXED (fixed9), image62, 0, 0);
  gtk_widget_set_size_request (image62, 832, 456);

  button_home_list_ouv = gtk_button_new ();
  gtk_widget_show (button_home_list_ouv);
  gtk_fixed_put (GTK_FIXED (fixed9), button_home_list_ouv, 464, 344);
  gtk_widget_set_size_request (button_home_list_ouv, 45, 35);

  image61 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image61);
  gtk_container_add (GTK_CONTAINER (button_home_list_ouv), image61);

  button_retour_aff_ouv = gtk_button_new ();
  gtk_widget_show (button_retour_aff_ouv);
  gtk_fixed_put (GTK_FIXED (fixed9), button_retour_aff_ouv, 264, 344);
  gtk_widget_set_size_request (button_retour_aff_ouv, 100, 35);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button_retour_aff_ouv), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image41 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image41);
  gtk_box_pack_start (GTK_BOX (hbox22), image41, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox22), label62, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) O_treeview, "row_activated",
                    G_CALLBACK (on_treeview_ouvrier_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_home_list_ouv, "clicked",
                    G_CALLBACK (on_button_home_list_ouv_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_aff_ouv, "clicked",
                    G_CALLBACK (on_button_retour_aff_ouv_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage_ouvrier, affichage_ouvrier, "affichage_ouvrier");
  GLADE_HOOKUP_OBJECT (affichage_ouvrier, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (affichage_ouvrier, O_treeview, "O_treeview");
  GLADE_HOOKUP_OBJECT (affichage_ouvrier, image62, "image62");
  GLADE_HOOKUP_OBJECT (affichage_ouvrier, button_home_list_ouv, "button_home_list_ouv");
  GLADE_HOOKUP_OBJECT (affichage_ouvrier, image61, "image61");
  GLADE_HOOKUP_OBJECT (affichage_ouvrier, button_retour_aff_ouv, "button_retour_aff_ouv");
  GLADE_HOOKUP_OBJECT (affichage_ouvrier, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (affichage_ouvrier, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (affichage_ouvrier, image41, "image41");
  GLADE_HOOKUP_OBJECT (affichage_ouvrier, label62, "label62");

  return affichage_ouvrier;
}

GtkWidget*
create_avancement (void)
{
  GtkWidget *avancement;
  GtkWidget *fixed10;
  GtkWidget *image49;
  GtkWidget *entry_cin_avancement;
  GtkWidget *label74;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label73;
  GtkWidget *label_out_avancement;
  GtkWidget *button_retour_avancement;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image51;
  GtkWidget *label77;
  GtkWidget *button_confirmer_avancement;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image50;
  GtkWidget *label76;

  avancement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (avancement), _("Avancement"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (avancement), fixed10);

  image49 = create_pixmap (avancement, "unnamed.png");
  gtk_widget_show (image49);
  gtk_fixed_put (GTK_FIXED (fixed10), image49, 160, 0);
  gtk_widget_set_size_request (image49, 424, 480);

  entry_cin_avancement = gtk_entry_new ();
  gtk_widget_show (entry_cin_avancement);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_cin_avancement, 40, 160);
  gtk_widget_set_size_request (entry_cin_avancement, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin_avancement), 8226);

  label74 = gtk_label_new (_("Taux d'avancement"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed10), label74, 16, 208);
  gtk_widget_set_size_request (label74, 150, 25);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton1, 168, 208);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label73 = gtk_label_new (_("<span foreground=\"red\"><b>Veuillez inserer le CIN de l'ouvrier </b></span>"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed10), label73, 8, 128);
  gtk_widget_set_size_request (label73, 270, 17);
  gtk_label_set_use_markup (GTK_LABEL (label73), TRUE);

  label_out_avancement = gtk_label_new (_("<span foreground=\"red\"><b></b></span>"));
  gtk_widget_show (label_out_avancement);
  gtk_fixed_put (GTK_FIXED (fixed10), label_out_avancement, 8, 320);
  gtk_widget_set_size_request (label_out_avancement, 300, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_out_avancement), TRUE);

  button_retour_avancement = gtk_button_new ();
  gtk_widget_show (button_retour_avancement);
  gtk_fixed_put (GTK_FIXED (fixed10), button_retour_avancement, 128, 272);
  gtk_widget_set_size_request (button_retour_avancement, 80, 30);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (button_retour_avancement), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image51 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image51);
  gtk_box_pack_start (GTK_BOX (hbox30), image51, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox30), label77, FALSE, FALSE, 0);

  button_confirmer_avancement = gtk_button_new ();
  gtk_widget_show (button_confirmer_avancement);
  gtk_fixed_put (GTK_FIXED (fixed10), button_confirmer_avancement, 16, 272);
  gtk_widget_set_size_request (button_confirmer_avancement, 100, 30);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button_confirmer_avancement), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image50 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image50);
  gtk_box_pack_start (GTK_BOX (hbox29), image50, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox29), label76, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_retour_avancement, "clicked",
                    G_CALLBACK (on_button_retour_avancement_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_confirmer_avancement, "clicked",
                    G_CALLBACK (on_button_confirmer_avancement_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (avancement, avancement, "avancement");
  GLADE_HOOKUP_OBJECT (avancement, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (avancement, image49, "image49");
  GLADE_HOOKUP_OBJECT (avancement, entry_cin_avancement, "entry_cin_avancement");
  GLADE_HOOKUP_OBJECT (avancement, label74, "label74");
  GLADE_HOOKUP_OBJECT (avancement, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (avancement, label73, "label73");
  GLADE_HOOKUP_OBJECT (avancement, label_out_avancement, "label_out_avancement");
  GLADE_HOOKUP_OBJECT (avancement, button_retour_avancement, "button_retour_avancement");
  GLADE_HOOKUP_OBJECT (avancement, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (avancement, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (avancement, image51, "image51");
  GLADE_HOOKUP_OBJECT (avancement, label77, "label77");
  GLADE_HOOKUP_OBJECT (avancement, button_confirmer_avancement, "button_confirmer_avancement");
  GLADE_HOOKUP_OBJECT (avancement, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (avancement, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (avancement, image50, "image50");
  GLADE_HOOKUP_OBJECT (avancement, label76, "label76");

  return avancement;
}

GtkWidget*
create_abscence_indiv (void)
{
  GtkWidget *abscence_indiv;
  GtkWidget *fixed11;
  GtkWidget *label78;
  GtkWidget *treeview_abs_indiv;
  GtkWidget *image52;
  GtkWidget *label_cin_abs_indiv;
  GtkWidget *button_retour_indiv;
  GtkWidget *alignment35;
  GtkWidget *hbox35;
  GtkWidget *image66;
  GtkWidget *label83;

  abscence_indiv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abscence_indiv), _("Abscence individuel"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (abscence_indiv), fixed11);

  label78 = gtk_label_new (_("<span foreground=\"red\"><b>Abscence pour l'ouvrier de CIN num : </b></span>"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed11), label78, 72, 24);
  gtk_widget_set_size_request (label78, 280, 25);
  gtk_label_set_use_markup (GTK_LABEL (label78), TRUE);

  treeview_abs_indiv = gtk_tree_view_new ();
  gtk_widget_show (treeview_abs_indiv);
  gtk_fixed_put (GTK_FIXED (fixed11), treeview_abs_indiv, 56, 88);
  gtk_widget_set_size_request (treeview_abs_indiv, 300, 200);

  image52 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image52);
  gtk_fixed_put (GTK_FIXED (fixed11), image52, 416, 352);
  gtk_widget_set_size_request (image52, 16, 16);

  label_cin_abs_indiv = gtk_label_new (_("<span foreground=\"blue\"><b></b></span>"));
  gtk_widget_show (label_cin_abs_indiv);
  gtk_fixed_put (GTK_FIXED (fixed11), label_cin_abs_indiv, 128, 48);
  gtk_widget_set_size_request (label_cin_abs_indiv, 150, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_cin_abs_indiv), TRUE);

  button_retour_indiv = gtk_button_new ();
  gtk_widget_show (button_retour_indiv);
  gtk_fixed_put (GTK_FIXED (fixed11), button_retour_indiv, 176, 312);
  gtk_widget_set_size_request (button_retour_indiv, 100, 40);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (button_retour_indiv), alignment35);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox35);

  image66 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image66);
  gtk_box_pack_start (GTK_BOX (hbox35), image66, FALSE, FALSE, 0);

  label83 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (hbox35), label83, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_abs_indiv, "row_activated",
                    G_CALLBACK (on_treeview_abs_indiv_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_retour_indiv, "clicked",
                    G_CALLBACK (on_button_retour_indiv_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abscence_indiv, abscence_indiv, "abscence_indiv");
  GLADE_HOOKUP_OBJECT (abscence_indiv, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (abscence_indiv, label78, "label78");
  GLADE_HOOKUP_OBJECT (abscence_indiv, treeview_abs_indiv, "treeview_abs_indiv");
  GLADE_HOOKUP_OBJECT (abscence_indiv, image52, "image52");
  GLADE_HOOKUP_OBJECT (abscence_indiv, label_cin_abs_indiv, "label_cin_abs_indiv");
  GLADE_HOOKUP_OBJECT (abscence_indiv, button_retour_indiv, "button_retour_indiv");
  GLADE_HOOKUP_OBJECT (abscence_indiv, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (abscence_indiv, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (abscence_indiv, image66, "image66");
  GLADE_HOOKUP_OBJECT (abscence_indiv, label83, "label83");

  return abscence_indiv;
}

