/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *ajout_ouvrier;
  GtkWidget *gestion_ouvrier;
  GtkWidget *supprime_ouvrier;
  GtkWidget *modifier_ouvrier;
  GtkWidget *consulter_ouvrier;
  GtkWidget *ouvrier_mois;
  GtkWidget *affichage_abscence;
  GtkWidget *affichage_ouvrier;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 /* ajout_ouvrier = create_ajout_ouvrier ();
  gtk_widget_show (ajout_ouvrier);*/
  gestion_ouvrier = create_gestion_ouvrier ();
  gtk_widget_show (gestion_ouvrier);
  /*supprime_ouvrier = create_supprime_ouvrier ();
  gtk_widget_show (supprime_ouvrier);
  modifier_ouvrier = create_modifier_ouvrier ();
  gtk_widget_show (modifier_ouvrier);
  consulter_ouvrier = create_consulter_ouvrier ();
  gtk_widget_show (consulter_ouvrier);
  ouvrier_mois = create_ouvrier_mois ();
  gtk_widget_show (ouvrier_mois);
  affichage_abscence = create_affichage_abscence ();
  gtk_widget_show (affichage_abscence);
  affichage_ouvrier = create_affichage_ouvrier ();
  gtk_widget_show (affichage_ouvrier);*/

  gtk_main ();
  return 0;
}

